apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: springboot
  labels:
    app: spring-boot-demo
  name: spring-boot-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-demo
    spec:
      serviceAccountName: jenkins-robot
      containers:
      - image: docker.io/vogetisameer12/spring-boot-demo
        name: spring-boot-demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: springboot
  labels:
    app: spring-boot-demo
  name: spring-boot-demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-demo
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-boot-demo
  namespace: springboot
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /spring-boot-demo
        backend:
          serviceName: spring-boot-demo
          servicePort: 8080
